on:
  push:
    branches:
      - master

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Install Packages
      run: |
        npm install

    - name: make test-coverage
      run: |
        make test-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true
